//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MizaniaData.Data
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json; 
    
    public partial class PorteFeuille
    {
        public PorteFeuille()
        {
            this.Categorie = new HashSet<Categorie>();
            this.Utilisateur = new HashSet<Utilisateur>();
        }
    
        public int id { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> dateCreation { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<Categorie> Categorie { get; set; }
        [JsonIgnore]
        public virtual ICollection<Utilisateur> Utilisateur { get; set; }
    }
}
